import esbuild from 'esbuild';
const production = process.argv[2] === 'production';
const context = await esbuild.context({
  entryPoints: ['main.ts'], bundle: true, external: ['obsidian'],
  format: 'cjs', platform: 'browser', target: 'es2021',
  outfile: 'main.js', sourcemap: production ? false : 'inline',
  minify: production, logLevel: 'info',
  banner: { js: '/* Thought Inbox | MIT | Generated by esbuild. See source repository. */' }
});
if (production) { await context.rebuild(); await context.dispose(); }
else { await context.watch(); }
