import { readFile, access } from 'node:fs/promises';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const json = async path => JSON.parse(await readFile(path, 'utf8'));
const manifest = await json('manifest.json'), pkg = await json('package.json'), versions = await json('versions.json');
assert.match(manifest.id, /^[a-z0-9]+(?:-[a-z0-9]+)*$/);
assert.ok(!manifest.id.includes('obsidian'));
assert.equal(manifest.version, pkg.version); assert.equal(versions[manifest.version], manifest.minAppVersion);
assert.match(manifest.version, /^\d+\.\d+\.\d+$/); assert.match(manifest.minAppVersion, /^\d+\.\d+\.\d+$/);
assert.ok(manifest.description.length <= 250 && manifest.description.endsWith('.'));
assert.equal(manifest.isDesktopOnly, false);
for (const file of ['main.js', 'styles.css', 'main.ts', 'README.md', 'LICENSE', 'CHANGELOG.md', 'package-lock.json', '.github/workflows/release.yml']) await access(file);
const bundle = await readFile('main.js', 'utf8');
const script = new vm.Script(bundle, { filename: 'main.js' });
const module = { exports: {} };
const host = { Plugin: class {}, Modal: class {}, ItemView: class {}, PluginSettingTab: class {} };
script.runInNewContext({ module, exports: module.exports, require: name => { assert.equal(name, 'obsidian'); return host; } });
assert.equal(typeof module.exports.default, 'function');
const external = [...bundle.matchAll(/require\(["']([^"']+)["']\)/g)].map(m => m[1]);
assert.ok(external.length && external.every(name => name === 'obsidian'));
assert.ok(!/\b(fetch|requestUrl|XMLHttpRequest|WebSocket)\s*\(/.test(bundle));
console.log(`Release verified: ${manifest.name} ${manifest.version}; minAppVersion ${manifest.minAppVersion}; CommonJS; sole runtime dependency: obsidian.`);
